
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 9000
spring:
  application:
      name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: STUDENT-SERVICE
        uri:
          lb://STUDENT-SERVICE
        predicates:
        - Path=/student/**
      - id: INSTITUTE-SERVICE
        uri:
          lb://INSTITUTE-SERVICE
        predicates:
        - Path=/Institute/**